### ISSUE TITLE
Mark mandatory settings with "*"

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#21]
First shot: via .text files
Second shot (if possible): infer from model

**Comment by Elscha** [comment]
Initial Implementation comitted in SSEHUB/EASyProducer@7e3e9764cc79766f88dbabb305ee0e7f8e546d22

**Comment by Elscha** [comment]
Initial version now works with the qualimaster model since SSEHUB/EASyProducer@f62df77076474a2ebc27de29068da456f0b677cd

**Comment by eichelbe** [comment]
Looks nice. May need some refinements ;)
BTW, NPE on Infrastructure:
java.lang.NullPointerException
	at de.uni_hildesheim.sse.model.varModel.filter.mandatoryVars.MandatoryDeclarationClassifier.visitOclFeatureCall(MandatoryDeclarationClassifier.java:416)
	at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.accept(OCLFeatureCall.java:398)
	at de.uni_hildesheim.sse.model.varModel.filter.mandatoryVars.MandatoryDeclarationClassifier.visitOclFeatureCall(MandatoryDeclarationClassifier.java:416)
	at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.accept(OCLFeatureCall.java:398)
	at de.uni_hildesheim.sse.model.varModel.filter.mandatoryVars.MandatoryDeclarationClassifier.visitDecisionVariableDeclaration(MandatoryDeclarationClassifier.java:142)
	at de.uni_hildesheim.sse.model.varModel.DecisionVariableDeclaration.accept(DecisionVariableDeclaration.java:54)
	at de.uni_hildesheim.sse.model.varModel.AbstractProjectVisitor.visitProject(AbstractProjectVisitor.java:80)
	at de.uni_hildesheim.sse.model.varModel.Project.accept(Project.java:434)
...

**Comment by Elscha** [comment]
NPE solved, progress:
SSEHUB/EASyProducer@f62df77076474a2ebc27de29068da456f0b677cd
SSEHUB/EASyProducer@83b57b74b370d5b9021188bf9ccfbfd6a1f17a73
SSEHUB/EASyProducer@63c8706843a40941419322c39a87bcc5542a4c5b
SSEHUB/EASyProducer@4bf5ce0cdb6ac58059e28d01e7db0d211cff40fd
SSEHUB/EASyProducer@91779e3bb2e7c94b5f8f86aa454f751f7527c746

**Comment by eichelbe** [comment]
Show "'" in pipeline editor...

**Comment by Elscha** [comment]
Changed strategy of MandatoryClassifier in
SSEHUB/EASyProducer@d81a92d9446fc53bb5975a52fb7ffedc87e922e9

**Comment by eichelbe** [comment]
Looks better then the old version ;)
At a glance, missed the following:
- family: members
- machine: memory, frequency, ports, role

**Comment by eichelbe** [comment]
Just as a reminder... shall also apply to the property editors of the pipeline editor (via LabelProvider of PipelineDiagramElementPropertyEditorCreator, tricky use of temporary models for accessing the EASy editors)

**Comment by eichelbe** [comment]
Another hint... in DataManagement, the now mandatory setting of the strategy may cause a transitive mandatory requirement for the dependent variables :o

**Comment by Elscha** [comment]
Family: mebers should not be consideres with commit SSEHUB/EASyProducer@3a7e9fbc98dcbec1762b6cd10b3891b61935f10d

**Comment by Elscha** [comment]
Preparation for PipelineEditor in: SSEHUB/EASyProducer@3cc40a7d3c464291622b43d4b39c361658675b3f
Bug fix for DerivedDatatypes in in SSEHUB/EASyProducer@9686f7e70e6dfec7db223e6d1df4939ea1d95a54
SSEHUB/EASyProducer@960cd7c6ddcc00b45084c5e52b0d81a839cacc94
