### ISSUE TITLE
Check user M2_HOME

### ISSUE THREAD

**Issue by rsizonenko** [QualiMaster/QM-IConf#69]
M2_HOME was set to Maven installation folder (write protected). That produced access denied error (described below). After changing to MAVEN_HOME the problem is gone.

When clicking "implimenting class" of Algorithm Browse button

java.lang.NullPointerException
	at eu.qualimaster.manifestUtils.ManifestConnection.getJarFiles(ManifestConnection.java:1492)
	at eu.qualimaster.manifestUtils.ManifestConnection.getAllValidClasses(ManifestConnection.java:1476)
	at de.uni_hildesheim.sse.qmApp.editors.ClassEditor.browseButtonSelected(ClassEditor.java:121)
	at de.uni_hildesheim.sse.qmApp.editors.AbstractTextSelectionEditorCreator$ArtifactComposite$1.widgetSelected(AbstractTextSelectionEditorCreator.java:152)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at de.uni_hildesheim.sse.qmApp.Application.start(Application.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by eichelbe** [comment]
Changed to M2_REPO
http://maven.40175.n5.nabble.com/What-value-do-I-set-M2-REPO-to-td95009.html

Resolution:
  - M2_REPO exists, use that
  - else as maven does, consider user.home
  - forget C:\ (!) [Linux]
